// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDemLpfcrPGIR---vuVkPSax74gx7br24Q',
    appId: '1:124887924696:web:71d309ef7087f5d878bcad',
    messagingSenderId: '124887924696',
    projectId: 'movies-4b7a9',
    authDomain: 'movies-4b7a9.firebaseapp.com',
    storageBucket: 'movies-4b7a9.appspot.com',
    measurementId: 'G-1MSQ21NY32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgXCViTbFdT-Dz4FTAkJo8h4z3vdNDRs8',
    appId: '1:124887924696:android:8c99b485365890d278bcad',
    messagingSenderId: '124887924696',
    projectId: 'movies-4b7a9',
    storageBucket: 'movies-4b7a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb-Rz5cbFERqRz-mn0shRXqna6TEdWJuc',
    appId: '1:124887924696:ios:7914aef815a522e478bcad',
    messagingSenderId: '124887924696',
    projectId: 'movies-4b7a9',
    storageBucket: 'movies-4b7a9.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb-Rz5cbFERqRz-mn0shRXqna6TEdWJuc',
    appId: '1:124887924696:ios:7914aef815a522e478bcad',
    messagingSenderId: '124887924696',
    projectId: 'movies-4b7a9',
    storageBucket: 'movies-4b7a9.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemLpfcrPGIR---vuVkPSax74gx7br24Q',
    appId: '1:124887924696:web:d3231a610a1aca1178bcad',
    messagingSenderId: '124887924696',
    projectId: 'movies-4b7a9',
    authDomain: 'movies-4b7a9.firebaseapp.com',
    storageBucket: 'movies-4b7a9.appspot.com',
    measurementId: 'G-HPGJBLQQ4E',
  );
}
